export const API_GENERIC = 'API_GENERIC';

// News
export const GET_NEWS_STORIES = 'GET_NEWS_STORIES';
export const GET_NEWS_STORIES_SUCCESS = 'GET_NEWS_STORIES_SUCCESS';
export const GET_NEWS_STORIES_ERROR = 'GET_NEWS_STORIES_ERROR';
export const GET_NEWS_STORIES_DETAILS = 'GET_NEWS_STORIES_DETAILS';
export const GET_NEWS_STORIES_DETAILS_SUCCESS = 'GET_NEWS_STORIES_DETAILS_SUCCESS';
export const GET_NEWS_STORIES_DETAILS_ERROR = 'GET_NEWS_STORIES_DETAILS_ERROR';

// Top stories
export const GET_TOP_STORIES = 'GET_TOP_STORIES';
export const GET_TOP_STORIES_SUCCESS = 'GET_TOP_STORIES_SUCCESS';
export const GET_TOP_STORIES_ERROR = 'GET_TOP_STORIES_ERROR';
export const GET_TOP_STORIES_DETAILS = 'GET_TOP_STORIES_DETAILS';
export const GET_TOP_STORIES_DETAILS_SUCCESS = 'GET_TOP_STORIES_DETAILS_SUCCESS';
export const GET_TOP_STORIES_DETAILS_ERROR = 'GET_TOP_STORIES_DETAILS_ERROR';
