export const API_GENERIC = 'API_GENERIC';
export const GET_STORIES_DETAILS = 'GET_STORIES_DETAILS';
export const GET_STORIES_DETAILS_SUCCESS = 'GET_STORIES_DETAILS_SUCCESS';
export const GET_STORIES_DETAILS_ERROR = 'GET_STORIES_DETAILS_ERROR';

// News
export const GET_NEWS_STORIES = 'GET_NEWS_STORIES';
export const GET_NEWS_STORIES_SUCCESS = 'GET_NEWS_STORIES_SUCCESS';
export const GET_NEWS_STORIES_ERROR = 'GET_NEWS_STORIES_ERROR';

// Top stories
export const GET_TOP_STORIES = 'GET_TOP_STORIES';
export const GET_TOP_STORIES_SUCCESS = 'GET_TOP_STORIES_SUCCESS';
export const GET_TOP_STORIES_ERROR = 'GET_TOP_STORIES_ERROR';

// Ask stories
export const GET_ASK_STORIES = 'GET_ASK_STORIES';
export const GET_ASK_STORIES_SUCCESS = 'GET_ASK_STORIES_SUCCESS';
export const GET_ASK_STORIES_ERROR = 'GET_ASK_STORIES_ERROR';

// Show stories
export const GET_SHOW_STORIES = 'GET_SHOW_STORIES';
export const GET_SHOW_STORIES_SUCCESS = 'GET_SHOW_STORIES_SUCCESS';
export const GET_SHOW_STORIES_ERROR = 'GET_SHOW_STORIES_ERROR';

// Job stories
export const GET_JOBS_STORIES = 'GET_JOBS_STORIES';
export const GET_JOBS_STORIES_SUCCESS = 'GET_JOBS_STORIES_SUCCESS';
export const GET_JOBS_STORIES_ERROR = 'GET_JOBS_STORIES_ERROR';
